### ISSUE TITLE
bug on UserCardDismissAnimationController

### ISSUE THREAD

**Issue by adelbios** [Ramotion/garland-view#6]
when I use navagationController  present UserCardViewController ok that's right ?
so when go back ( dismiss) to ViewController  I got black screen after animation completed
 
[ScreenRecording_07-03-2018 14-06-06.MP4.zip](https://github.com/Ramotion/garland-view/files/2159142/ScreenRecording_07-03-2018.14-06-06.MP4.zip)

**Comment by adelbios** [comment]
I fixit.... the solution .....
1- go to `UserCardDismissAnimationController`

**replace this line** 
`let toVC = transitionContext.viewController(forKey: UITransitionContextViewControllerKey.to)! as? GarlandViewController`

**INTO**
`let toVC = transitionContext.viewController(forKey: UITransitionContextViewControllerKey.to)!`

2- add property to  `UserCardDismissAnimationController`
`var   rootViewController : GarlandViewController?`

3-  replace 

`  func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        self.selectedCardIndex = indexPath
        let cardController = UserCardViewController.init(nibName: "UserCardViewController", bundle: nil)
        present(cardController, animated: true, completion: nil)
    }`

** INTO**

`  func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        self.selectedCardIndex = indexPath
        let cardController = UserCardViewController.init(nibName: "UserCardViewController", bundle: nil)
        cardController.userCardDismissAnimationController.rootViewController = self
        present(cardController, animated: true, completion: nil)
    }`

**Comment by ikolpachkov** [comment]
@adelbios Hello!) please take a look at the commit (1d2edfbfac5fdfeb354130e2ece29d9c7cc0c916), I've added fallback alpha animation it will help you with black screen. And of course you can also use your solution. 
I think it does not make much sense to change the original transition in the example
